trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsRegion: 'us-east-1'
  ecrRegistry: 'AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com'
  imageName: 'DOCKER_IMAGE_NAME'

stages:
- stage: Build
  displayName: 'Build and Push to AWS ECR'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    steps:
    - checkout: self
      submodules: true

    - task: AWSCLI@1
      displayName: 'Install AWS CLI'
      inputs:
        awsCredentials: 'AWSServiceConnection'
        regionName: '$(awsRegion)'
        awsCommand: 'ecr'
        awsSubCommand: 'get-login-password'
        awsArguments: '--region $(awsRegion)'
      name: awsLogin

    - task: Bash@3
      displayName: 'Login to Amazon ECR'
      inputs:
        targetType: 'inline'
        script: |
          aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(ecrRegistry)
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - task: Bash@3
      displayName: 'Generate timestamp'
      inputs:
        targetType: 'inline'
        script: |
          TIMESTAMP=$(date +'%H%M%S%d%m%Y')
          echo "##vso[task.setvariable variable=imageTag]$TIMESTAMP"
          echo "Generated tag: $TIMESTAMP"

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: $(ecrRegistry)/$(imageName)
        tags: |
          $(imageTag)
          latest
        Dockerfile: '**/Dockerfile'

    - task: Docker@2
      displayName: 'Push Docker image with timestamp'
      inputs:
        command: push
        repository: $(ecrRegistry)/$(imageName)
        tags: $(imageTag)

    - task: Docker@2
      displayName: 'Push Docker image as latest'
      inputs:
        command: push
        repository: $(ecrRegistry)/$(imageName)
        tags: latest

    - task: Bash@3
      displayName: 'Trigger webhook'
      inputs:
        targetType: 'inline'
        script: |
          curl -fS -X POST $(WEBHOOK_ENDPOINT)
      env:
        WEBHOOK_ENDPOINT: $(WEBHOOK_ENDPOINT)
