trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'DOCKER_USERNAME/DOCKER_IMAGE_NAME'

stages:
- stage: Build
  displayName: 'Build and Push to Docker Hub'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    steps:
    - checkout: self
      submodules: true

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'DockerHub'

    - task: Bash@3
      displayName: 'Generate timestamp'
      inputs:
        targetType: 'inline'
        script: |
          TIMESTAMP=$(date +'%H%M%S%d%m%Y')
          echo "##vso[task.setvariable variable=imageTag]$TIMESTAMP"
          echo "Generated tag: $TIMESTAMP"

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: $(dockerImageName)
        tags: |
          $(imageTag)
          latest
        Dockerfile: '**/Dockerfile'

    - task: Docker@2
      displayName: 'Push Docker image with timestamp'
      inputs:
        command: push
        repository: $(dockerImageName)
        tags: $(imageTag)

    - task: Docker@2
      displayName: 'Push Docker image as latest'
      inputs:
        command: push
        repository: $(dockerImageName)
        tags: latest

    - task: Bash@3
      displayName: 'Trigger webhook'
      inputs:
        targetType: 'inline'
        script: |
          curl -fS -X POST $(WEBHOOK_ENDPOINT)
      env:
        WEBHOOK_ENDPOINT: $(WEBHOOK_ENDPOINT)
