trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  quayRegistry: 'quay.io'
  imageName: 'QUAY_USERNAME/DOCKER_IMAGE_NAME'
  fullImageName: '$(quayRegistry)/$(imageName)'

stages:
- stage: Build
  displayName: 'Build and Push to Quay.io'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    steps:
    - checkout: self
      submodules: true

    - task: Docker@2
      displayName: 'Login to Quay.io'
      inputs:
        command: login
        containerRegistry: 'QuayRegistry'

    - task: Bash@3
      displayName: 'Generate timestamp'
      inputs:
        targetType: 'inline'
        script: |
          TIMESTAMP=$(date +'%H%M%S%d%m%Y')
          echo "##vso[task.setvariable variable=imageTag]$TIMESTAMP"
          echo "Generated tag: $TIMESTAMP"

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: $(fullImageName)
        tags: |
          $(imageTag)
          latest
        Dockerfile: '**/Dockerfile'

    - task: Docker@2
      displayName: 'Push Docker image with timestamp'
      inputs:
        command: push
        repository: $(fullImageName)
        tags: $(imageTag)

    - task: Docker@2
      displayName: 'Push Docker image as latest'
      inputs:
        command: push
        repository: $(fullImageName)
        tags: latest

    - task: Bash@3
      displayName: 'Trigger webhook'
      inputs:
        targetType: 'inline'
        script: |
          curl -fS -X POST $(WEBHOOK_ENDPOINT)
      env:
        WEBHOOK_ENDPOINT: $(WEBHOOK_ENDPOINT)
