name: Build and Push to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: DOCKER_USERNAME/DOCKER_IMAGE_NAME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
            submodules: 'true'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "tag=$(date +'%H%M%S%d%m%Y')" >> $GITHUB_OUTPUT

      - name: Build and push
        working-directory: ./
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}
          docker push ${{ env.IMAGE_NAME }}:latest
          echo "Published: ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}"

      - name: Trigger webhook
        run: curl -fS -X POST ${{secrets.WEBHOOK_ENDPOINT}}
