name: Build and Push to GitLab Container Registry

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GITLAB_REGISTRY: registry.gitlab.com
  IMAGE_NAME: GITLAB_GROUP/GITLAB_PROJECT/DOCKER_IMAGE_NAME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
            submodules: 'true'

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "tag=$(date +'%H%M%S%d%m%Y')" >> $GITHUB_OUTPUT

      - name: Build and push
        working-directory: ./
        run: |
          docker build -t ${{ env.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }} .
          docker tag ${{ env.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }} ${{ env.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}
          docker push ${{ env.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          echo "Published: ${{ env.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}"

      - name: Trigger webhook
        run: curl -fS -X POST ${{secrets.WEBHOOK_ENDPOINT}}
